version: '3.3'
services:
  age_transform:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: age_transform
    command : uvicorn scripts.main:app --host 0.0.0.0 --reload --port 6080
    # command: gunicorn scripts.main:app --preload --host 0.0.0.0 --port 7090
    # command: gunicorn scripts.main:app -w 1 --preload --timeout 180 -k uvicorn.workers.UvicornWorker -b "0.0.0.0:6080" # if you skip -k uvicorn.workers.UvicornWorker, the program will show error => findout why
    # command: gunicorn scripts.main:app -w 1 --timeout 180 -k uvicorn.workers.UvicornWorker -b "0.0.0.0:6090"
    ports:
      - "6080:6080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
