version: '3.3'
services:
  age_transform:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: age_transform
    command: gunicorn scripts.main:app -w 1 --timeout 180 -k uvicorn.workers.UvicornWorker -b "0.0.0.0:6090"
    ports:
      - "6090:6080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
