version: '3.3'
services:
  age_transform:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: age_transform
    # command: gunicorn scripts.main:app --preload --host 0.0.0.0 --port 7090
    command: gunicorn scripts.main:app --preload -b age_transform:7090
    # command: gunicorn scripts.main:app -w 1 --timeout 180 -k uvicorn.workers.UvicornWorker -b "0.0.0.0:6090"
    ports:
      - "7090:7090"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
